apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: transaction-monitoring
  title: Transaction Monitoring
  description: Monitors transactions of potentially fraudulent activity
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: group:fraud-and-compliance
  system: monitor
  subcomponentOf: monitor